# @package dataset.low_quality_effect.random
#### IF mode random
random_effects:
  max_effect: 4
  min_effect: 1

equalizer:
  proba: 0.55
  freq_mean: 2000
  freq_std: 700
  db_min: 10
  db_max: 22

bass:
  proba: 0.2
  freq_min: 50
  freq_max: 1500
  db_min: 12
  db_max: 22

treble:
  proba: 0.2
  freq_min: 3000
  freq_max: 10000
  db_min: 12
  db_max: 22

overdrive:
  proba: 0.15
  min_int: 1
  max_int: 8

reverb:
  proba: 0.2
  proba_w: 0.
  proba_delay: 0.3


flanger:
  proba: 0.1

# tremolo:
#   proba: 0.1
#   speed_min: 100 # in Hz
#   speed_max: 12000 
#   depth_min : 10 # in %
#   depth_max : 90

echo:
  proba: 0.2
  proba_next_echo: 0.5
  gain_in_min: 0.9
  gain_in_max: 1.
  gain_out_min: 0.1
  gain_out_max: 0.9
  delay_max: 500 #in milliseconds, must be inferior to length audio
  delay_min: 100
  decay_min: 0.1
  decay_max: 0.9


riaa:
  proba: 0.1

hilbert:
  proba: 0.1

sinc:
  proba: 0.1
  att_max: 100 #in dB
  max_freq: 8000
  min_freq: 450

band:
  proba: 0.1
  max_freq: 8000
  min_freq: 500
  noise_proba: 0.3








