# @package dataset.low_quality_effect.train
mode: set   # list of effects given in parameters, could be mode: random

# Create several modified versions of the HQ audio
# Space separated
# equalizer, freq, Q factor, gain db
# bass gain, freq, q factor
# overdrive, gain db, colour db

effects:
###### TRAIN
  - name: '0'
    params:
      - "equalizer 200 0.7 20"
      - "equalizer 450 20 30"
      - "treble -20 4000 1"  # high-cut
  
  - name: '1'
    params:
      - "bass -20 800 1" # low-cut
      - "equalizer 2000 10 -30"
      - "equalizer 3000 0.7 25"

  - name: '2'
    params:
      - "bass -20 1200 1" # low-cut
      - "equalizer 3000 10 -20"
      - "equalizer 5000 0.7 20"
      - "overdrive 10 9"

  - name: '3'
    params:
      - "bass -10 1000 1" # low-cut
      - "equalizer 4000 10 -30"
      - "equalizer 5000 0.7 25"

  - name: '4'
    params:
      - "equalizer 2000 0.7 20"
      - "equalizer 750 10 20"
      - "treble -20 8500 1"  # high-cut

  - name: '5'
    params:
      - "equalizer 300 2 10"
      - "equalizer 950 10 -15"
      - "treble -30 8000 1"  # high-cut
      - "overdrive 5 7"

  - name: '6'
    params:
      - "equalizer 800 1 20"
      - "equalizer 1550 10 20"
      - "treble -20 8000 1"  # high-cut

  - name: '7'
    params:
      - "equalizer 400 0.8 20"
      - "equalizer 550 10 10"
      - "treble -35 7500 1"  # high-cut

  - name: '8'
    params:
      - "equalizer 450 0.7 -10"
      - "equalizer 1050 20 20"
      - "treble -20 9800 1"  # high-cut
      - "overdrive 5 6"

  - name: '9'
    params:
      - "bass -8 1000 1" # low-cut
      - "equalizer 2000 10 -30"
      - "equalizer 5000 3 10"
      - "equalizer 6000 0.7 20"
      - "treble -35 7500 1"  # high-cut


