# @package dataset.low_quality_effect.validation
mode: set   # list of effects given in parameters, could be mode: random

# Create several modified versions of the HQ audio
# Space separated
# equalizer, freq, Q factor, gain db
# bass gain, freq, q factor
# overdrive, gain db, colour db

effects:
### VALIDATION
  - name: '15'
    params:
      - "equalizer 200 0.7 20"
      - "equalizer 450 20 30"
      - "treble -30 4000 1"  # high-cut
  
  - name: '16'
    params:
      - "bass -30 800 1" # low-cut
      - "equalizer 2000 10 -30"
      - "equalizer 3000 0.7 25"

  - name: '17'
    params:
      - "bass -30 800 1" # low-cut
      - "equalizer 2000 10 -30"
      - "equalizer 3000 0.7 25"
      - "overdrive 10 10"

  - name: '18'
    params:
      - "bass -10 1000 1" # low-cut
      - "equalizer 4000 10 -30"
      - "equalizer 5000 0.7 25"

  - name: '19'
    params:
      - "equalizer 2000 0.7 20"
      - "equalizer 750 20 30"
      - "treble -20 3500 1"  # high-cut