defaults:
  - base_dataset
  - low_quality_effect/train
  - low_quality_effect/test
  - low_quality_effect/validation
  - low_quality_effect/random
  
mode: audio
audio_format: wav
sample_rate: 22050
match_sample_rate: false # If False, import all audio file irrelevant of sample rate
mono: true

name: maestro
high_quality_path: /scratch/data_audio/maestro/maestro
#/mnt/scitas/datasets/audio/maestro/maestro_full
# high_quality_path: /work/vita/datasets/audio/maestro/2018-44k
# high_quality_path: /work/vita/datasets/audio/maestro/2018-small
low_quality_path: /mnt/scitas/datasets/audio/maestro/lq

collated_path: /scratch/data_audio/maestro/${dataset.name}_collated_file.csv #/mnt/scitas/datasets/audio/maestro/${dataset.name}_full_collated_V100.csv
use_collated_file: true
no_lq_file: true

use_user_lq_files: false  # if false generates LQ files from set of equalizers
fallback_generated_eqs: true  # if can't match HQ file, default is true
user_lq_suffix: '_test_eq'

# Low quality effects
use_random_effects: false
max_training_effects: 0
normalize_inputs_post_eq: false

# If generated from EQ
persist_low_quality_files: false
force_overwrite_lq_files: false