defaults:
  - base_trainer
name: gta_diffusion
platform: slurm
type: cityscape

train: True #train from scratch
eval: False #load ckpt.pt and evaluate FID and IS
# Dataset
datapath: /work/vita/datasets/gta5 #help='dataset path if downloaded
dataset: GTA #help='dataset name')
split: all
corruption:  #help=corruption type base on Imagenet-C
corruption_severity:  #help='corruption severity level 1-5'
random_flip: False #help='Whether to use random flip in training')
lower_image_size: [270,430]
img_size: [256, 256] #help='image size')

# UNet
input_channel: 3
kernel_size: 3
ch: 128  #help='base channel of UNet')
ch_mult: [1, 1, 1, 1, 2, 2, 4, 8] #help='channel multiplier')
attn: [2,3,4] #help='add attention to these levels')
num_res_blocks: 3 #help='# resblock in each level')
dropout: 0.1 #help='dropout rate of resblock')

# Gaussian Diffusion
beta_1: 1e-4 #help='start beta value')
beta_T: 0.02 #help='end beta value')
T: 1000 #help='total diffusion steps')
mean_type: epsilon #['xprev', 'xstart', 'epsilon'], help='predict variable')
var_type: 'fixedlarge' #['fixedlarge', 'fixedsmall'], help='variance type')
# Training
lr: 1e-3 #help='target learning rate')
grad_clip: 1. #help="gradient norm clipping")
total_steps: 1000000 #help='total training steps')
warmup: 5000 #help='learning rate warmup')
batch_size: 4 #help='batch size')
num_workers: 2 #help='workers of Dataloader')
ema_decay: 0.9999 #help="ema decay rate")
parallel: True #help='multi gpu training')
unique_img: False #help='Train a model on a single image.')
accumulating_step: 10
#Mixed Precision
use_half_for_matmul: False
use_half_for_conv: False
use_half_precision: False

# Logging & Sampling
logdir: /work/vita/bastien/logs/GTA #help='log directory')
wandb_entity: bastienvd #help='wandb id to use')
sample_size: 8 #"sampling size of images")
sample_step: 10000 #help='frequency of sampling')
ml_exp_name: GTA_Diffusion_scitas #help = 'name of the experience on wandb')
checkpointpath: #/mnt/scitas/bastien/logs/Audio/ckpt_350000.pt

# Evaluation
save_step: 50000 #help='frequency of saving checkpoints, 0 to disable during training')
eval_step: 0 #help='frequency of evaluating model, 0 to disable during training')
num_images: 50000 #help='the number of generated images for evaluation')
fid_use_torch: False #help='calculate IS and FID on gpu')
fid_cache: ./stats/cifar10.train.npz #help='FID cache')

# Mode slurm
slurm:
  nodes: 4 # 2
  gpus_per_node: 2  # max 2
  cpus_per_task: 10
  mem: 72 # in GiB 48
  timeout: 48 # hours
  partition: gpu
  qos: gpu
  account: vita # optional
  reservation: vita-neurips
